version: '2'
services:
    foo-postgresql:
        container_name: foo-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/foo/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=foo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
