version: '2'
services:
    app3-app:
        image: app3
        external_links:
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
