version: '2'
services:
    uaa-app:
        image: uaa
        external_links:
            - uaa-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/uaa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    uaa-postgresql:
        extends:
            file: postgresql.yml
            service: uaa-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
