version: '2'
services:
    uaa-postgresql:
        container_name: uaa-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/uaa/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=uaa
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
