version: '2'
services:
    jhipster-opscenter:
        container_name: jhipster-opscenter
        build:
            context: opscenter/
        ports:
            - 8888:8888
    gateway-cassandra:
        container_name: gateway-cassandra
        build:
            context: .
            dockerfile: cassandra/Cassandra-OpsCenter.Dockerfile
        # volumes:
        #     - ~/volumes/jhipster/gateway/cassandra/:/var/lib/cassandra/data
        links:
            - jhipster-opscenter:opscenter
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    gateway-cassandra-node:
        build:
            context: .
            dockerfile: cassandra/Cassandra-OpsCenter.Dockerfile
        links:
            - gateway-cassandra:seed
            - jhipster-opscenter:opscenter
        environment:
            - CASSANDRA_SEEDS=seed
